# Generated by Django 3.1.4 on 2022-04-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route code', models.CharField(default='', max_length=10)),
                ('time generated', models.DateField()),
                ('Geo code list', models.TextField(default='')),
                ('addrs list', models.TextField(default='')),
            ],
        ),
    ]
