# Generated by Django 3.1.4 on 2022-04-03 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='Geo code list',
        ),
        migrations.RemoveField(
            model_name='route',
            name='addrs list',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route code',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time generated',
        ),
        migrations.AddField(
            model_name='route',
            name='addrs',
            field=models.TextField(default='', verbose_name='addr list'),
        ),
        migrations.AddField(
            model_name='route',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='route code'),
        ),
        migrations.AddField(
            model_name='route',
            name='geo_codes',
            field=models.TextField(default='', verbose_name='Geo code list'),
        ),
        migrations.AddField(
            model_name='route',
            name='time_generated',
            field=models.DateField(default=datetime.date.today, verbose_name='time generated'),
        ),
    ]
