# Generated by Django 3.1.4 on 2022-04-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20220402_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image_url',
            field=models.CharField(default='', max_length=200, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='route',
            name='total_dist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total distance'),
        ),
    ]
