# Generated by Django 3.1.4 on 2022-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20220406_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='total_time',
            field=models.CharField(default='', max_length=50, verbose_name='route time'),
        ),
    ]
